[package]
name = "banshee-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[build-dependencies]
tauri-build.workspace = true

[dependencies]
anyhow.workspace = true
banshee-core = { path = "../../../packages/core" }
serde.workspace = true
tauri.workspace = true
tokio.workspace = true
tracing.workspace = true

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-global-shortcut = "2"

[features]
default = []
gpu-vulkan = ["banshee-core/gpu-vulkan"]
