[package]
name = "banshee-stt"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
default = []
gpu-vulkan = ["whisper-rs/vulkan"]

[dependencies]
anyhow.workspace = true
banshee-contracts = { path = "../contracts" }
serde.workspace = true
thiserror.workspace = true
whisper-rs.workspace = true
